version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./go-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    env_file:
      - ./go-backend/.env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/fall_detection
      - REDIS_URL=redis:6379
    volumes:
      - ./go-backend/tmp:/app/tmp
      - ./go-backend/storage:/app/storage

  web-app:
    build:
      context: ./web-app
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1
        - NEXT_PUBLIC_STREAM_URL=http://localhost:8080/streams
    ports:
      - "3000:3000"
    env_file:
      - ./web-app/.env
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1
      - NEXT_PUBLIC_STREAM_URL=http://localhost:8080/streams
    depends_on:
      - backend

volumes:
  mongo_data:
