# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fall_detection.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fall_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66\x61ll_detection.proto\x12\rfalldetection\"\x1a\n\x05\x46rame\x12\x11\n\tkeypoints\x18\x01 \x03(\x02\"4\n\x0c\x46rameRequest\x12$\n\x06\x66rames\x18\x01 \x03(\x0b\x32\x14.falldetection.Frame\"\xb2\x01\n\x0e\x41nalysisResult\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12G\n\rprobabilities\x18\x03 \x03(\x0b\x32\x30.falldetection.AnalysisResult.ProbabilitiesEntry\x1a\x34\n\x12ProbabilitiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32U\n\x0c\x46\x61llDetector\x12\x45\n\x07\x41nalyze\x12\x1b.falldetection.FrameRequest\x1a\x1d.falldetection.AnalysisResultB\x12Z\x10./;falldetectionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fall_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\020./;falldetection'
  _globals['_ANALYSISRESULT_PROBABILITIESENTRY']._loaded_options = None
  _globals['_ANALYSISRESULT_PROBABILITIESENTRY']._serialized_options = b'8\001'
  _globals['_FRAME']._serialized_start=39
  _globals['_FRAME']._serialized_end=65
  _globals['_FRAMEREQUEST']._serialized_start=67
  _globals['_FRAMEREQUEST']._serialized_end=119
  _globals['_ANALYSISRESULT']._serialized_start=122
  _globals['_ANALYSISRESULT']._serialized_end=300
  _globals['_ANALYSISRESULT_PROBABILITIESENTRY']._serialized_start=248
  _globals['_ANALYSISRESULT_PROBABILITIESENTRY']._serialized_end=300
  _globals['_FALLDETECTOR']._serialized_start=302
  _globals['_FALLDETECTOR']._serialized_end=387
# @@protoc_insertion_point(module_scope)
